name       : filezilla
version    : 3.31.0
release    : 38
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.31.0_src.tar.bz2 : 14c568b7e3331b8ae6d2371aeb4f4b43fbf97f057c0af9d75165d0d8d0d2dee5
license    : GPL-2.0
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

