name       : filezilla
version    : 3.24.0
release    : 29
source     :
    - https://nchc.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.24.0/FileZilla_3.24.0_src.tar.bz2 : 3d5dd4899cdeca038afd330f24098a61a223f15b172611e0c210244911cd4cad
license    : GPL-2.0
component  : network.clients
summary    : The Free FTP Solution
description: |
    Open Source FTP Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
