name        : filezilla
version     : 3.13.1
release     : 15
source     :
    - http://internode.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.13.1/FileZilla_3.13.1_src.tar.bz2 : c16e7dc9f6b6663ff67de608df930148d693b61e70d76783a81db710f117e8c7
license     : GPL-2.0+
summary     : The Free FTP Solution
builddeps   :
    - pkgconfig(dbus-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pkgconfig(gnutls)
    - wxwidgets-devel
    - pugixml-devel
    - xdg-utils
description : |
    Open Source FTP Client
setup      : |
    %configure --disable-manualupdatecheck --disable-autoupdatecheck --disable-static --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
