name       : filezilla
version    : 3.34.0
release    : 42
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.34.0_src.tar.bz2 : 637ea551a442e22d8ee862b0f035077d37ba823a4372e8d0fcbd5b0e378bea80
license    : GPL-2.0-or-later
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
