name       : filezilla
version    : 3.25.0
release    : 30
source     :
    - https://nchc.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.25.0/FileZilla_3.25.0_src.tar.bz2 : 104e5f302dfef72cf9d235a880da159c93c9378ebfc48487ef07a1ba7f5834ac
license    : GPL-2.0
component  : network.clients
summary    : The Free FTP Solution
description: |
    Open Source FTP Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
