name       : filezilla
version    : 3.57.0
release    : 67
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.57.0_src.tar.bz2 : 82bf6c7077ca13012549356b463952f124ee04876f21e4ba720acc9811c899c7
license    : GPL-2.0-or-later
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
libsplit   : no
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(pugixml)
    - pkgconfig(sqlite3)
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %patch -p1 < $pkgfiles/filezilla-3.47.2.1-interface_Mainfrm_h_include_list.patch

    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
