name       : filezilla
version    : 3.25.2
release    : 32
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.25.2_src.tar.bz2 : 559b0adbc1aff862dddbce95ed8a4a854c7a255b1de79efba9eabe459381aacd
license    : GPL-2.0
component  : network.clients
summary    : The Free FTP Solution
description: |
    Open Source FTP Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
