name       : filezilla
version    : 3.35.2
release    : 45
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.35.2_src.tar.bz2 : c4d82544894c1aa3ef32ca05fe31af7d34ed0933cd864bf44857aa32157ce6ac
license    : GPL-2.0-or-later
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
