name        : filezilla
version     : 3.17.0.1
release     : 22
source     :
    - http://jaist.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.17.0.1/FileZilla_3.17.0.1_src.tar.bz2 : 47914f9c8935e5497871642540b250a09b7e4ea4f6944d37add20fed2d50232a
license     : GPL-2.0
component   : network.clients
summary     : The Free FTP Solution
description : |
    Open Source FTP Client
builddeps   :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
