name        : filezilla
version     : 3.12.0
release     : 11
source     :
    - http://internode.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.12.0/FileZilla_3.12.0_src.tar.bz2 : f31a664d418ae5d8fc27027c6bfdd94bb8c489e6f4dc3059d92ee366965fc2f5
clang       : no
license     : GPL-2.0+
summary     : The Free FTP Solution
builddeps   :
    - pkgconfig(dbus-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pkgconfig(gnutls)
    - wxwidgets-devel
    - xdg-utils
description : |
    Open Source FTP Client
setup      : |
    %configure --disable-manualupdatecheck --disable-autoupdatecheck --disable-static --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
