name       : filezilla
version    : 3.21.0
release    : 26
source     :
    - http://netcologne.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.21.0/FileZilla_3.21.0_src.tar.bz2 : 209bcdfcd60ae2278fa2fa8d99421682e0db146add9e96cb1e8455c3378c80e4
license    : GPL-2.0
component  : network.clients
summary    : The Free FTP Solution
description: |
    Open Source FTP Client
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
