name       : filezilla
version    : 3.37.4
release    : 48
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.37.4_src.tar.bz2 : 71bc4778b89facc48adbb1265621fbabff09aac9554e1b5945a1404de3f13c99
license    : GPL-2.0-or-later
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
