name       : filezilla
version    : 3.35.1
release    : 44
source     :
    - https://download.filezilla-project.org/client/FileZilla_3.35.1_src.tar.bz2 : 8c99d39ecfdb892d13ee13200003f260a55cbbd6d2be161fad3e137454f15f84
license    : GPL-2.0-or-later
component  : network.clients
summary    : The Free FTP Solution
description: |
    FileZilla is a FTP, FTPS, SFTP and SSH client with a lot of features.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(cppunit) # check
    - pkgconfig(dbus-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfilezilla)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pugixml-devel
    - wxwidgets-devel
    - xdg-utils
setup      : |
    %configure \
        --disable-static \
        --disable-autoupdatecheck \
        --disable-manualupdatecheck \
        --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
