name        : filezilla
version     : 3.12.0.2
release     : 12
source     :
    - http://jaist.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.12.0.2/FileZilla_3.12.0.2_src.tar.bz2 : 7a296fc2cd94d00d3a14ad29b84ff081c60a791f4cddc07f0bd8022bd57e1d0d
clang       : no
license     : GPL-2.0+
summary     : The Free FTP Solution
builddeps   :
    - pkgconfig(dbus-1)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
    - pkgconfig(atk)
    - pkgconfig(libidn)
    - pkgconfig(sqlite3)
    - pkgconfig(gnutls)
    - wxwidgets-devel
    - xdg-utils
description : |
    Open Source FTP Client
setup      : |
    %configure --disable-manualupdatecheck --disable-autoupdatecheck --disable-static --with-tinyxml=builtin
build      : |
    %make
install    : |
    %make_install
